## Github

In [1]:
!apt-get install git

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.12).
0 upgraded, 0 newly installed, 0 to remove and 20 not upgraded.

In [2]:
from google.colab import userdata

!git clone https://{userdata.get('GITHUB_USERNAME')}:{userdata.get('GITHUB_TOKEN')}@github.com/LffaZ/datawrang-studycase.git

Cloning into 'datawrang-studycase'...
remote: Enumerating objects: 49, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 49 (delta 6), reused 46 (delta 3), pack-reused 0 (from 0)
Receiving objects: 100% (49/49), 9.75 MiB | 20.90 MiB/s, done.
Resolving deltas: 100% (6/6), done.

In [4]:
from google.colab \
import drive
import os, glob

drive.mount(os.getcwd() + '/drive')
# !mv /content/drive/MyDrive/SD221137 Data Wrangling/studycase_1_2.ipynbstudycase_1_2.ipynb datawrang-studycase/notebooks

Mounted at /content/drive

# Study Case 1: Akses dari CSV

In [ ]:
!kaggle datasets download sid321axn/gold-price-prediction-dataset

Dataset URL: https://www.kaggle.com/datasets/sid321axn/gold-price-prediction-dataset
License(s): CC0-1.0
Downloading gold-price-prediction-dataset.zip to /content
  0% 0.00/371k [00:00<?, ?B/s]
100% 371k/371k [00:00<00:00, 71.3MB/s]

In [ ]:
!unzip gold-price-prediction-dataset.zip

Archive:  gold-price-prediction-dataset.zip
  inflating: FINAL_USO.csv

In [ ]:
import pandas as pd
df = pd.read_csv('FINAL_USO.csv')
df.head()

,Date,Open,High,Low,Close,Adj Close,Volume,SP_open,SP_high,SP_low,...,GDX_Low,GDX_Close,GDX_Adj Close,GDX_Volume,USO_Open,USO_High,USO_Low,USO_Close,USO_Adj Close,USO_Volume
0,2011-12-15,154.740005,154.949997,151.710007,152.330002,152.330002,21521900,123.029999,123.199997,121.989998,...,51.570000,51.680000,48.973877,20605600,36.900002,36.939999,36.049999,36.130001,36.130001,12616700
1,2011-12-16,154.309998,155.369995,153.899994,155.229996,155.229996,18124300,122.230003,122.949997,121.300003,...,52.040001,52.680000,49.921513,16285400,36.180000,36.500000,35.730000,36.270000,36.270000,12578800
2,2011-12-19,155.479996,155.860001,154.360001,154.869995,154.869995,12547200,122.059998,122.320000,120.029999,...,51.029999,51.169998,48.490578,15120200,36.389999,36.450001,35.930000,36.200001,36.200001,7418200
3,2011-12-20,156.820007,157.429993,156.580002,156.979996,156.979996,9136300,122.180000,124.139999,120.370003,...,52.369999,52.990002,50.215282,11644900,37.299999,37.610001,37.220001,37.560001,37.560001,10041600
4,2011-12-21,156.979996,157.529999,156.130005,157.160004,157.160004,11996100,123.930000,124.360001,122.750000,...,52.419998,52.959999,50.186852,8724300,37.669998,38.240002,37.520000,38.110001,38.110001,10728000

# Study Case 2: Akses dari Excel (3 Sheets)

In [ ]:
file_path = 'National_Data_Appendix.xlsx'

# Membaca semua sheet dalam file Excel
xls = pd.ExcelFile(file_path)

# Menampilkan nama sheet yang ada
print(xls.sheet_names)

# Membaca setiap sheet berdasarkan nama sheet
sheet1 = pd.read_excel(xls, sheet_name='Veteran')
sheet2 = pd.read_excel(xls, sheet_name='Non-Veteran')
sheet3 = pd.read_excel(xls, sheet_name='Recent Veteran VHA User')

sheet1.columns = sheet1.columns.str.replace('\n', ' ')
sheet2.columns = sheet2.columns.str.replace('\n', ' ')
sheet3.columns = sheet3.columns.str.replace('\n', ' ')

sheet1.columns = sheet1.columns.str.replace('Veteran ', '')
sheet1.head()

['Veteran', 'Non-Veteran', 'Recent Veteran VHA User']

,Year of Death,Age Group,Suicide Deaths,Population Estimate,"Crude Rate per 100,000",Male Suicide Deaths,Male Population Estimate,"Male Crude Rate per 100,000",Age Group 2,Female Suicide Deaths,Female Population Estimate,"Female Crude Rate per 100,000"
0,2005,18-34,544,2147000,25.337680,504,1779000,28.330523,18-34,40,368000,10.869565
1,2005,35-54,2059,7116000,28.934795,1948,6336000,30.744949,35-54,111,780000,14.230769
2,2005,55-74,1866,9976000,18.704892,1847,9626000,19.187617,55+,26,591000,4.399323
3,2005,75+,1315,5001000,26.294741,1308,4760000,27.478992,.,.,.,.
4,2005,Total,5787,24240000,23.873762,5610,22501000,24.932225,Total,177,1739000,10.178263

In [ ]:
sheet2.columns = sheet2.columns.str.replace('Non-Veteran ', '')
sheet2.head()

,Year of Death,Age Group,Suicide Deaths,Population Estimate,"Crude Rate per 100,000",Male Suicide Deaths,Male Population Estimate,"Male Crude Rate per 100,000",Age Group 2,Female Suicide Deaths,Female Population Estimate,"Female Crude Rate per 100,000"
0,2005,18-34,7911,62500330,12.657533,6492,30554577,21.247226,18-34,1419,31945753,4.441905
1,2005,35-54,11482,77890923,14.741127,8384,35304919,23.747399,35-54,3098,42586004,7.274691
2,2005,55-74,4688,38493473,12.178688,3343,13223458,25.280830,55+,1788,34986238,5.110581
3,2005,75+,1745,11399718,15.307396,1302,1683495,77.339107,.,.,.,.
4,2005,Total,25823,190284444,13.570736,19518,80766449,24.165975,Total,6305,109517995,5.757045

In [ ]:
sheet3.columns = sheet3.columns.str.replace('VHA Veteran ', '')
sheet3.head()

,Year of Death,Age Group,Suicide Deaths,Population Estimate,"Crude Rate per 100,000",Male Suicide Deaths,Male Population Estimate,"Male Crude Rate per 100,000",Female Suicide Deaths,Age Group 2,Female Population Estimate,"Female Crude Rate per 100,000"
0,2005,18-34,1638,5230872,31.314091,1582,4860127,32.550590,56,Total,370742,15.104844
1,2006,35-54,1733,5323518,32.534876,1700,4935484,34.424182,33,18-34,388032,8.504453
2,2007,55-74,1703,5379603,31.656611,1659,4974026,33.353264,44,35-54,405577,10.848741
3,2008,75+,1870,5454501,34.265279,1819,5030169,36.141927,51,NaN,424332,12.018891
4,2009,Total,1822,5627383,32.377395,1768,5181672,34.120261,54,Total,445711,12.115474

In [ ]:
df_combined = pd.concat([sheet1, sheet2, sheet3], ignore_index=True)
df_combined.head()

,Year of Death,Age Group,Suicide Deaths,Population Estimate,"Crude Rate per 100,000",Male Suicide Deaths,Male Population Estimate,"Male Crude Rate per 100,000",Age Group 2,Female Suicide Deaths,Female Population Estimate,"Female Crude Rate per 100,000"
0,2005,18-34,544,2147000,25.337680,504,1779000,28.330523,18-34,40,368000,10.869565
1,2005,35-54,2059,7116000,28.934795,1948,6336000,30.744949,35-54,111,780000,14.230769
2,2005,55-74,1866,9976000,18.704892,1847,9626000,19.187617,55+,26,591000,4.399323
3,2005,75+,1315,5001000,26.294741,1308,4760000,27.478992,.,.,.,.
4,2005,Total,5787,24240000,23.873762,5610,22501000,24.932225,Total,177,1739000,10.178263

In [ ]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143 entries, 0 to 142
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Year of Death                  143 non-null    int64
 1   Age Group                      143 non-null    object
 2   Suicide Deaths                 143 non-null    int64
 3   Population Estimate            143 non-null    int64
 4   Crude Rate per 100,000         143 non-null    float64
 5   Male Suicide Deaths            143 non-null    int64
 6   Male Population Estimate       143 non-null    int64
 7   Male Crude Rate per 100,000    143 non-null    float64
 8   Age Group 2                    141 non-null    object
 9   Female Suicide Deaths          143 non-null    object
 10  Female Population Estimate     143 non-null    object
 11  Female Crude Rate per 100,000  143 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 13.5+ KB